### ISSUE TITLE
why write this instead of using ccxt or https://github.com/JKorf/CryptoExchange.Net ?

### ISSUE THREAD

**Issue by llvm-x86** [hugomorg/crypto_exchange_apis#4]
https://github.com/JKorf/CryptoExchange.Net

**Comment by hugomorg** [comment]
Hi @llvm-x86, I don't use C# :)

**Comment by llvm-x86** [comment]
> Hi @llvm-x86, I don't use C# :)

Sorry let me speak honestly for you.

hugomorg: "Hi @llvm-x86 sorry I'm a retarded communist."
